export interface Property {
  address;
  trustee;
  county;
  auctionTime;
  startingBid;
  saleStatus;
  onWebsite;
  verifiedAddress;
  googlePlaceId;
  zpid;
  zillowLow;
  zillowHigh;
  actualWorth;
  zillowSquareFeet;
  zillowLotSize;
  zillowBeds;
  zillowBaths;
  zillowUrl;
  condition;
  calculatedRepairCosts;
}
